# Generated by Django 2.2.6 on 2019-10-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
