# Generated by Django 2.2.6 on 2019-10-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20191016_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cotent',
            new_name='content',
        ),
    ]
