# Generated by Django 2.2.6 on 2019-10-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20191021_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='likes_users',
            new_name='like_users',
        ),
    ]
