# Generated by Django 2.2.6 on 2019-10-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_auto_20191016_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
